In [2]:
import pandas as pd

In [3]:
df1 = pd.read_excel('Tweet stream.xlsx')
# this has 1.6million tweets containing apple stock

In [4]:
df1.head()

,Tweet Id,Date,Hour,User Name,Nickname,Bio,Tweet content,Favs,RTs,Latitude,...,Listed,Tweet language (ISO 639-1),Tweet Url,Is a RT,Original Tweet User Name,User Mentions,Hashtags,Symbols,Media,URLs
0,743056393796739072,2016-06-15,12:23,Sufiy,Sufiy,#Investing as a way of life based on common se...,RT @kirillklip: Race for #renewable #energy #t...,NaN,4.0,NaN,...,537.0,da,http://www.twitter.com/Sufiy/status/7430563937...,True,@kirillklip,@kirillklip,"#renewable,#energy,#technologies,#lithium,#hed...","$LIT,$ILV.v,$TSLA,$AAPL",NaN,http://www.bnn.ca/News/2016/5/7/Race-for-renew...
1,743055905214889984,2016-06-15,12:21,Breaking News,HotpageNews,One Stop Shop for BREAKING AND TRENDING NEWS. ...,#APPLE TRIES to Limit #Google Incursions Onto ...,NaN,NaN,42.35843,...,163.0,en,http://www.twitter.com/HotpageNews/status/7430...,False,NaN,NaN,"#APPLE,#Google","$AAPL,$GOOG",NaN,http://hotpagenews.com/r/150730
2,743055905193857024,2016-06-15,12:21,Hotpage News,Hotpage_News,The One Stop WEBSITE for Breaking and Trending...,#APPLE TRIES to Limit #Google Incursions Onto ...,NaN,NaN,NaN,...,427.0,en,http://www.twitter.com/Hotpage_News/status/743...,False,NaN,NaN,"#APPLE,#Google","$AAPL,$GOOG",NaN,http://hotpagenews.com/r/150730
3,743055497725673472,2016-06-15,12:20,Danny,TraderDanny77,"Family Man, entrepreneur, wanna be trader, Tha...",What calls do I sell on $twtr\n\n$spy $aapl $g...,NaN,NaN,46.47747,...,5.0,en,http://www.twitter.com/TraderDanny77/status/74...,False,NaN,NaN,NaN,"$twtr,$spy,$aapl,$googl,$tsla,$ibm,$wba,$scty,...",NaN,NaN
4,743055311909441536,2016-06-15,12:19,Jayson,hovastocks,Father | Investor in life | Runner | Cyclist,Good for $AAPL pay? https://t.co/6EuitFi8Au,NaN,NaN,NaN,...,20.0,en,http://www.twitter.com/hovastocks/status/74305...,False,NaN,NaN,NaN,$AAPL,NaN,https://twitter.com/businessinsider/status/742...

In [5]:
df1 = df1.drop([
    'Hour', 'User Name', 'Nickname', 'Bio', 'Favs', 'RTs', 'Latitude',
    'Longitude', 'Country', 'Place (as appears on Bio)', 'Profile picture',
    'Following', 'Listed', 'Tweet language (ISO 639-1)', 'Tweet Url',
    'Is a RT', 'Original Tweet User Name', 'User Mentions', 'Hashtags',
    'Symbols', 'Media', 'URLs'
],
               axis=1)

In [6]:
# this is the coloumns after dropping
df1.columns

Index(['Tweet Id', 'Date', 'Tweet content', 'Followers'], dtype='object')

In [7]:
#View of df after dropping
df1.head()

,Tweet Id,Date,Tweet content,Followers
0,743056393796739072,2016-06-15,RT @kirillklip: Race for #renewable #energy #t...,1798
1,743055905214889984,2016-06-15,#APPLE TRIES to Limit #Google Incursions Onto ...,222
2,743055905193857024,2016-06-15,#APPLE TRIES to Limit #Google Incursions Onto ...,16177
3,743055497725673472,2016-06-15,What calls do I sell on $twtr\n\n$spy $aapl $g...,87
4,743055311909441536,2016-06-15,Good for $AAPL pay? https://t.co/6EuitFi8Au,387

In [ ]:
# this is the code for extracting the date and cumulatively taking the tweets for the entire day and taking the sum of its followers in that day

datadict={}
followerdict={}
datelist=df1.Date.unique()
count=0
temp=[]
follower_count=0
for i in range(len(df1.index)):
    if datelist[count]==df1.iloc[i]['Date']:
        temp.append(df1.iloc[i]['Tweet content'])
        follower_count+=df1.iloc[i]['Followers']
    else:
        datadict[datelist[count]]=temp
        followerdict[datelist[count]]=follower_count
        count+=1
        temp=[]
        follower_count=0
        temp.append(df1.iloc[i]['Tweet content'])
        follower_count+=df1.iloc[i]['Followers']

In [ ]:
#seeing the number of tweets for one particular day, i.e. 2016-06-07
len(datadict['2016-06-07'])

In [ ]:
datadict.keys()

In [ ]:
len(df1.Date.unique())

In [ ]:
df1.Date.unique()

In [ ]:
for i in datadict.keys():
    datadict[i]="".join(datadict[i])

In [ ]:
# datadict['2016-04-06']

In [48]:
def get_nrc_data():
    nrc = "NRC-emotion-lexicon-wordlevel-alphabetized-v0.92.txt"
    count=0
    emotion_dict=dict()
    with open(nrc,'r') as f:
        all_lines = list()
        for line in f:
            if count < 46:
                count+=1
                continue
            line = line.strip().split('\t')
            if int(line[2]) == 1:
                if emotion_dict.get(line[0]):
                    emotion_dict[line[0]].append(line[1])
                else:
                    emotion_dict[line[0]] = [line[1]]
    return emotion_dict


def emotion_analyzer(text,emotion_dict=get_nrc_data()):
    #Set up the result dictionary
    emotions = {x for y in emotion_dict.values() for x in y}
    emotion_count = dict()
    for emotion in emotions:
        emotion_count[emotion] = 0

    #Analyze the text and normalize by total number of words
    total_words = len(text.split())
    for word in text.split():
        if emotion_dict.get(word):
            for emotion in emotion_dict.get(word):
                emotion_count[emotion] += 1/len(text.split())
    return emotion_count

def comparative_emotion_analyzer(text_tuples,object_name="Tweets",print_output=False):
    if print_output:
        print("%-20s %1s\t%1s %1s %1s %1s   %1s %1s %1s %1s"%(object_name,
                                                              "fear","trust","negative","positive",
                                                              "joy","disgust","anticip", "sadness",
                                                              "surprise"))
    import pandas as pd
    df = pd.DataFrame(columns=[object_name,'Fear','Trust','Negative',
                           'Positive','Joy','Disgust','Anticipation',
                           'Sadness','Surprise'],)
    df.set_index(object_name,inplace=True)
    
    output = df    
    for text_tuple in text_tuples:
        text = text_tuple[1] 
        result = emotion_analyzer(text)
        if print_output:
            print("%-20s %1.2f\t%1.2f\t%1.2f\t%1.2f\t%1.2f\t%1.2f\t%1.2f\t%1.2f\t%1.2f"%(
                text_tuple[1][0:20],result['fear'],result['trust'],
                  result['negative'],result['positive'],result['joy'],result['disgust'],
                  result['anticipation'],result['sadness'],result['surprise']))
        df.loc[text_tuple[0]] = [result['fear'],result['trust'],
                  result['negative'],result['positive'],result['joy'],result['disgust'],
                  result['anticipation'],result['sadness'],result['surprise']]
    return output

In [49]:
df1 = pd.DataFrame(columns=['Fear','Trust','Negative',
                           'Positive','Joy','Disgust','Anticipation',
                           'Sadness','Surprise','follower_count'])
for i in datadict.keys():
#     print(i)
    df=comparative_emotion_analyzer([[i,datadict[i]]],object_name='Apple Tweets',print_output=False)
    df1=df1.append(df,ignore_index=False)

df1.head()

/Users/xiyuyang/anaconda3/lib/python3.6/site-packages/pandas/core/frame.py:6211: FutureWarning: Sorting because non-concatenation axis is not aligned. A future version
of pandas will change to not sort by default.

To accept the future behavior, pass 'sort=False'.

To retain the current behavior and silence the warning, pass 'sort=True'.

  sort=sort)

,Anticipation,Disgust,Fear,Joy,Negative,Positive,Sadness,Surprise,Trust,follower_count
2016-06-15,0.001800,0.001800,0.000900,0.000000,0.009001,0.004500,0.000000,0.001800,0.002700,NaN
2016-06-14,0.007916,0.000609,0.001827,0.005074,0.008930,0.010757,0.002030,0.005277,0.009539,NaN
2016-06-13,0.012598,0.000900,0.005399,0.005174,0.006974,0.026772,0.002475,0.004274,0.016423,NaN
2016-06-12,0.008077,0.008582,0.003534,0.001514,0.019687,0.008582,0.001514,0.001514,0.004543,NaN
2016-06-11,0.007812,0.001465,0.004883,0.002930,0.011719,0.009277,0.003418,0.003906,0.005859,NaN

In [50]:
for i in followerdict.keys():
    df1.follower_count.loc[i]=followerdict[i]

/Users/xiyuyang/anaconda3/lib/python3.6/site-packages/pandas/core/indexing.py:189: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  self._setitem_with_indexer(indexer, value)

In [51]:
df1.head()

,Anticipation,Disgust,Fear,Joy,Negative,Positive,Sadness,Surprise,Trust,follower_count
2016-06-15,0.001800,0.001800,0.000900,0.000000,0.009001,0.004500,0.000000,0.001800,0.002700,212332
2016-06-14,0.007916,0.000609,0.001827,0.005074,0.008930,0.010757,0.002030,0.005277,0.009539,4413122
2016-06-13,0.012598,0.000900,0.005399,0.005174,0.006974,0.026772,0.002475,0.004274,0.016423,2652364
2016-06-12,0.008077,0.008582,0.003534,0.001514,0.019687,0.008582,0.001514,0.001514,0.004543,647515
2016-06-11,0.007812,0.001465,0.004883,0.002930,0.011719,0.009277,0.003418,0.003906,0.005859,744268

In [52]:
from pandas_datareader import data as web
import datetime
start=datetime.datetime(2016, 3, 10)
end=datetime.datetime(2016, 6, 15)
print(start,end)

dfyahoo= web.DataReader(['AAPL','GOOGL'], 'yahoo', start, end)
rets = dfyahoo['Open'].pct_change()

2016-03-10 00:00:00 2016-06-15 00:00:00

In [53]:
import numpy as np
df1['Pct_change']=np.nan
# [i[:9] for i in rets.index.values()]

In [54]:
a=[str(i)[:10] for i in rets.index.values]

In [55]:
for i in followerdict.keys():
    if i in a:
        df1.Pct_change.loc[i]=rets.AAPL.loc[i]

/Users/xiyuyang/anaconda3/lib/python3.6/site-packages/pandas/core/indexing.py:189: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  self._setitem_with_indexer(indexer, value)

In [56]:
df1

,Anticipation,Disgust,Fear,Joy,Negative,Positive,Sadness,Surprise,Trust,follower_count,Pct_change
2016-06-15,0.001800,0.001800,0.000900,0.000000,0.009001,0.004500,0.000000,0.001800,0.002700,212332,0.005138
2016-06-14,0.007916,0.000609,0.001827,0.005074,0.008930,0.010757,0.002030,0.005277,0.009539,4413122,-0.013882
2016-06-13,0.012598,0.000900,0.005399,0.005174,0.006974,0.026772,0.002475,0.004274,0.016423,2652364,0.001624
2016-06-12,0.008077,0.008582,0.003534,0.001514,0.019687,0.008582,0.001514,0.001514,0.004543,647515,NaN
2016-06-11,0.007812,0.001465,0.004883,0.002930,0.011719,0.009277,0.003418,0.003906,0.005859,744268,NaN
2016-06-10,0.010336,0.001723,0.003302,0.003445,0.006029,0.008613,0.003302,0.003302,0.005024,6054195,0.000305
2016-06-07,0.003610,0.000000,0.000903,0.002708,0.005415,0.006318,0.000000,0.000000,0.007220,305868,0.012858
2016-06-06,0.010871,0.001004,0.004850,0.003680,0.009032,0.015053,0.002676,0.002843,0.010871,5499488,0.002045
2016-06-05,0.008673,0.004337,0.004337,0.003903,0.015611,0.015178,0.010841,0.003903,0.012576,1851030,NaN
2016-06-04,0.006410,0.005698,0.012108,0.002849,0.019231,0.022792,0.006410,0.002849,0.006410,390035,NaN
2016-06-03,0.008374,0.001092,0.004915,0.005097,0.010559,0.015110,0.006554,0.005461,0.010377,6452887,0.001947
2016-06-02,0.012309,0.002238,0.003730,0.004849,0.012495,0.013801,0.004849,0.005035,0.013614,4112753,-0.014341
2016-06-01,0.011114,0.000667,0.003112,0.002000,0.006890,0.013559,0.001111,0.004001,0.006224,2873846,-0.005823
2016-05-31,0.013740,0.002147,0.003435,0.002362,0.006655,0.006655,0.002147,0.004508,0.006870,1165054,0.001609
2016-05-30,0.015553,0.005354,0.007904,0.010454,0.007904,0.015043,0.007394,0.011729,0.017083,1402642,NaN
2016-05-29,0.026459,0.012600,0.003780,0.018480,0.002940,0.021000,0.005880,0.021420,0.021000,2005982,NaN
2016-05-28,0.017787,0.004941,0.011858,0.009881,0.005435,0.014822,0.008399,0.017787,0.023715,288882,NaN
2016-05-27,0.012437,0.000491,0.007364,0.005236,0.011455,0.017509,0.005236,0.004255,0.014400,5657352,-0.002408
2016-05-26,0.012001,0.002197,0.014875,0.006254,0.019777,0.020115,0.006930,0.005071,0.018594,4961737,0.010236
2016-05-25,0.015635,0.001445,0.002891,0.006701,0.004730,0.014321,0.003022,0.003416,0.009460,7092360,0.014915
2016-05-24,0.022810,0.004489,0.006552,0.005824,0.017957,0.016501,0.009221,0.008372,0.011041,10420914,0.014082
2016-05-23,0.005848,0.001418,0.002127,0.002658,0.005139,0.008152,0.001418,0.001418,0.006025,3376756,0.012997
2016-05-22,0.007095,0.000443,0.005765,0.011086,0.007095,0.017295,0.003104,0.002661,0.015078,2123759,NaN
2016-05-21,0.005309,0.003318,0.006967,0.002654,0.009290,0.011281,0.000664,0.006967,0.008626,5787932,NaN
2016-05-20,0.009996,0.001764,0.007350,0.004410,0.010584,0.018227,0.003234,0.003381,0.010437,5357101,0.000000
2016-05-19,0.009824,0.004404,0.004291,0.006436,0.009146,0.016147,0.003613,0.005533,0.012534,9005807,0.005098
2016-05-18,0.014184,0.001055,0.004689,0.004689,0.013129,0.013480,0.005744,0.004572,0.009378,21848520,-0.004125
2016-05-17,0.009824,0.001387,0.003121,0.006472,0.007166,0.012483,0.003699,0.005663,0.010287,9402633,0.023379
2016-05-16,0.009402,0.002447,0.009660,0.010948,0.007857,0.021767,0.003478,0.001417,0.015714,8517389,0.026556
2016-05-15,0.016044,0.000251,0.001003,0.001755,0.006769,0.014791,0.001755,0.001253,0.013788,1803631,NaN
...,...,...,...,...,...,...,...,...,...,...,...
2016-04-28,0.012685,0.005452,0.007233,0.004673,0.012574,0.014132,0.005452,0.004673,0.010793,2486070,0.016771
2016-04-27,0.013446,0.002062,0.004751,0.004930,0.008874,0.016673,0.004034,0.003048,0.009502,10041337,-0.076124
2016-04-26,0.011185,0.001991,0.006066,0.004834,0.011848,0.012891,0.003318,0.002464,0.010900,10366985,-0.010381
2016-04-25,0.007043,0.000361,0.004424,0.002438,0.006230,0.009120,0.003251,0.002438,0.006501,2335541,-0.000095
2016-04-24,0.010884,0.000447,0.003280,0.008648,0.004175,0.018339,0.001938,0.001938,0.010288,3100593,NaN
2016-04-23,0.007741,0.001209,0.003387,0.002661,0.002661,0.009676,0.001451,0.004596,0.006773,4398740,NaN
2016-04-22,0.011584,0.003337,0.006864,0.006960,0.016112,0.016350,0.006864,0.004767,0.013252,22504935,-0.017956
2016-04-21,0.011035,0.001427,0.005119,0.005455,0.010657,0.013679,0.004406,0.003608,0.010657,20720069,0.002719
2016-04-20,0.011477,0.000998,0.004865,0.009232,0.008608,0.014596,0.001996,0.003119,0.006487,5471447,-0.011494
2016-04-19,0.009274,0.001747,0.005376,0.002554,0.007124,0.012634,0.004435,0.002285,0.008602,6117055,-0.009275
2016-04-18,0.005249,0.000893,0.002680,0.001899,0.005249,0.005361,0.002122,0.003015,0.005361,5079343,-0.028722
2016-04-17,0.006318,0.001053,0.002457,0.002106,0.004914,0.005967,0.001053,0.002808,0.010179,1426549,NaN
2016-04-16,0.006706,0.001032,0.002837,0.003095,0.004127,0.016508,0.002321,0.003869,0.009028,5741292,NaN
2016-04-15,0.012985,0.000666,0.004828,0.005161,0.006659,0.013817,0.001998,0.003496,0.010654,5615910,0.004390
2016-04-14,0.010691,0.000396,0.003960,0.002970,0.006731,0.009503,0.002376,0.003762,0.010097,2604839,0.007401
2016-04-13,0.013948,0.000809,0.006064,0.004851,0.009096,0.012937,0.005256,0.004245,0.011320,1257674,0.013353
2016-04-12,0.012350,0.001710,0.005890,0.004370,0.009690,0.011780,0.004560,0.004180,0.012540,1370910,0.003395
2016-04-11,0.008661,0.000787,0.005512,0.002047,0.008504,0.013543,0.003780,0.001890,0.009449,2335363,0.000551
2016-04-10,0.010800,0.000982,0.005400,0.003436,0.007855,0.008346,0.001964,0.004418,0.008346,253017,NaN
2016-04-09,0.013561,0.001769,0.006486,0.002358,0.012382,0.013561,0.002948,0.004717,0.013561,291816,NaN
2016-04-08,0.011632,0.000191,0.005530,0.004767,0.004005,0.012967,0.001907,0.005149,0.011060,2297802,-0.009459
2016-04-07,0.011669,0.002139,0.005834,0.003112,0.009529,0.016531,0.003890,0.003501,0.007001,3112113,-0.002540
2016-04-06,0.007459,0.000219,0.002413,0.003730,0.007679,0.008776,0.001536,0.003072,0.009434,5040818,0.006575
2016-04-05,0.008983,0.000642,0.003529,0.001925,0.006096,0.008341,0.004171,0.002567,0.005454,942575,-0.008241
2016-04-04,0.008965,0.003118,0.007991,0.003508,0.008380,0.007016,0.004483,0.004677,0.008186,3336352,0.015076
2016-04-03,0.004915,0.000000,0.008738,0.001092,0.001638,0.009831,0.000546,0.009831,0.012561,3260284,NaN
2016-04-02,0.002187,0.000000,0.003644,0.000000,0.005102,0.004373,0.000729,0.002187,0.004373,833434,NaN
2016-04-01,0.011417,0.001737,0.004716,0.001737,0.013651,0.013155,0.003475,0.004468,0.007694,1999362,-0.008567
2016-03-31,0.013947,0.001579,0.002368,0.005789,0.010789,0.017895,0.002105,0.002632,0.012632,1142140,0.009848
2016-03-30,0.008618,0.001034,0.002241,0.003619,0.009307,0.013961,0.002241,0.002241,0.011203,1608581,0.035847

In [57]:
df1.head()

,Anticipation,Disgust,Fear,Joy,Negative,Positive,Sadness,Surprise,Trust,follower_count,Pct_change
2016-06-15,0.001800,0.001800,0.000900,0.000000,0.009001,0.004500,0.000000,0.001800,0.002700,212332,0.005138
2016-06-14,0.007916,0.000609,0.001827,0.005074,0.008930,0.010757,0.002030,0.005277,0.009539,4413122,-0.013882
2016-06-13,0.012598,0.000900,0.005399,0.005174,0.006974,0.026772,0.002475,0.004274,0.016423,2652364,0.001624
2016-06-12,0.008077,0.008582,0.003534,0.001514,0.019687,0.008582,0.001514,0.001514,0.004543,647515,NaN
2016-06-11,0.007812,0.001465,0.004883,0.002930,0.011719,0.009277,0.003418,0.003906,0.005859,744268,NaN

In [58]:
df2=pd.read_excel('google-stream1.xlsx')

In [59]:
df2

,Tweet Id,Date,Hour,User Name,Nickname,Bio,Tweet content,Favs,RTs,Latitude,...,Listed,Tweet language (ISO 639-1),Tweet Url,Is a RT,Original Tweet User Name,User Mentions,Hashtags,Symbols,Media,URLs
0,743031249682477057,2016-06-15,10:43,kimweeks,kimweeks77,NaN,RT @johnscharts: Similar to $GOOGL: $NFLX is s...,NaN,2.0,NaN,...,7.0,en,http://www.twitter.com/kimweeks77/status/74303...,True,@johnscharts,@johnscharts,NaN,"$GOOGL,$NFLX",http://pbs.twimg.com/media/Ck_Gw_nWgAISZ37.jpg,NaN
1,743031012406394880,2016-06-15,10:42,BullishChartPatterns,johnscharts,Chart pattern trader. Tweeting with friends an...,Similar to $GOOGL: $NFLX is showing reversal s...,3.0,2.0,37.54812,...,87.0,en,http://www.twitter.com/johnscharts/status/7430...,False,NaN,NaN,NaN,"$GOOGL,$NFLX",http://pbs.twimg.com/media/Ck_Gw_nWgAISZ37.jpg,NaN
2,743030242688696321,2016-06-15,10:39,Advertising News,AdNewsUS,The World of Advertising and Marketing Ideas,"#consumer, #jobs New #OT rules | ""OVERTIME: It...",NaN,NaN,NaN,...,93.0,en,http://www.twitter.com/AdNewsUS/status/7430302...,False,NaN,@YouTube,"#consumer,#jobs,#OT",$GOOGL,NaN,https://youtu.be/UFJaDm720FU
3,743029037858234368,2016-06-15,10:35,ProTradersNews,ProTradersNews,News for Pro Traders,$GOOGL:\n\nIs Dallas the Next Destination for ...,NaN,NaN,NaN,...,103.0,en,http://www.twitter.com/ProTradersNews/status/7...,False,NaN,NaN,NaN,$GOOGL,NaN,http://www.StockNewsWires.com/2016/06/15/googl...
4,743028676883779584,2016-06-15,10:33,dailystockplays.com,DailyStockPlays,"Live Day Trading Calls, Daily Swing Trading Li...",Unusual Call Activity https://t.co/4jDlRqXapi ...,NaN,NaN,37.25022,...,120.0,en,http://www.twitter.com/DailyStockPlays/status/...,False,NaN,NaN,NaN,"$KR,$WFT,$LOW,$PYPL,$MGM,$VXX,$GLD,$IYR,$LVS,$...",NaN,http://www.dailystockplays.com/Unusual-Call-Op...
5,743028189421797376,2016-06-15,10:31,Mr.Incredible,IncredibleTrade,Stocks & Options Trader. My tweets & responses...,$SPY $FB $IWM $IBB $AMZN $GOOGL Pay Attention ...,NaN,NaN,NaN,...,352.0,en,http://www.twitter.com/IncredibleTrade/status/...,False,NaN,NaN,NaN,"$SPY,$FB,$IWM,$IBB,$AMZN,$GOOGL",NaN,http://www.bloomberg.com/news/articles/2016-06...
6,743019479056187393,2016-06-15,09:57,ProTradersNews,ProTradersNews,News for Pro Traders,$MSFT $AAPL $GOOGL:\n\nApple Tries to Limit Go...,NaN,NaN,NaN,...,103.0,en,http://www.twitter.com/ProTradersNews/status/7...,False,NaN,NaN,NaN,"$MSFT,$AAPL,$GOOGL",NaN,http://www.StockNewsWires.com/2016/06/15/msft-...
7,743017272495747072,2016-06-15,09:48,SmartHomeBrands,home_brands,"New, features and products for the smart home",Google Fiber explores Dallas https://t.co/lsdB...,NaN,NaN,40.82593,...,1.0,en,http://www.twitter.com/home_brands/status/7430...,False,NaN,NaN,NaN,"$GOOG,$GOOGL",NaN,http://seekingalpha.com/news/3188874-google-fi...
8,743016380648165376,2016-06-15,09:44,bored2tears,bored2tears,"Trader interested in breaking stocks, CRE, eco...",#YouTube is built on the back of stolen conten...,1.0,NaN,47.50012,...,924.0,en,http://www.twitter.com/bored2tears/status/7430...,False,NaN,NaN,"#YouTube,#MusicBiz","$AAPL,$GOOGL",http://pbs.twimg.com/media/Ck-5dVqWgAAoP8d.png,http://twitthat.com/2aIpc
9,743014162373193729,2016-06-15,09:35,TheExtraIncome,TheExtraIncome,Private Trader just to collect some money.. #h...,"Andreas Halvorsen Buys Facebook, Amazon, Maste...",NaN,NaN,41.89474,...,64.0,en,http://www.twitter.com/TheExtraIncome/status/7...,False,NaN,NaN,NaN,"$GOOGL,$MA,$AET,$TEVA,$ECA,$AMZN,$COG,$LLY,$FB",NaN,http://www.gurufocus.com/news/421330/affid/152113
10,743011904533188608,2016-06-15,09:26,trader whodont trade,diggingplatinum,NaN,RT @MarketsRecap: These 3 Stocks Will Surprise...,NaN,1.0,NaN,...,526.0,en,http://www.twitter.com/diggingplatinum/status/...,True,@MarketsRecap,@MarketsRecap,NaN,"$ADBE,$TTWO,$ANET,$AAPL,$AMZN,$FB,$GOOGL",NaN,http://goo.gl/yWr8F3
11,743011292127072257,2016-06-15,09:24,Tramch - ØªØ±Ø§Ù…Ø´,Tramch,#TranceFamily â€¢ #Digital #Marketing - #Adverti...,RT @Dealogic: $GOOGL buying $TWTR predicted to...,NaN,6.0,NaN,...,71.0,en,http://www.twitter.com/Tramch/status/743011292...,True,@Dealogic,@Dealogic,"#business,#market","$GOOGL,$TWTR,$MSFT,$LKND",NaN,http://on.mktw.net/237Ctwj
12,743010029658210304,2016-06-15,09:19,Foster Elliot Ltd.,FosterElliotLtd,Foster Elliot Ltd is a traditional firm that h...,RT @SAlphaTech: Google Fiber explores Dallas h...,NaN,1.0,NaN,...,217.0,en,http://www.twitter.com/FosterElliotLtd/status/...,True,@SAlphaTech,@SAlphaTech,NaN,"$GOOG,$GOOGL",NaN,http://seekingalpha.com/news/3188874-google-fi...
13,743007354879254528,2016-06-15,09:08,Seeking Alpha,SEEKINGALPHA_FS,NaN,Google Fiber explores Dallas https://t.co/FRVd...,NaN,NaN,NaN,...,89.0,en,http://www.twitter.com/SEEKINGALPHA_FS/status/...,False,NaN,NaN,NaN,"$GOOG,$GOOGL",NaN,http://seekingalpha.com/news/3188874-google-fi...
14,743007353688072192,2016-06-15,09:08,Tech Stocks,SAlphaTech,Breaking news and analysis about tech stocks f...,Google Fiber explores Dallas https://t.co/2NGy...,NaN,1.0,NaN,...,211.0,en,http://www.twitter.com/SAlphaTech/status/74300...,False,NaN,NaN,NaN,"$GOOG,$GOOGL",NaN,http://seekingalpha.com/news/3188874-google-fi...
15,743007352429805568,2016-06-15,09:08,Breaking News,MarketCurrents,Real-time stock market news from Seeking Alpha...,Google Fiber explores Dallas https://t.co/jqSd...,NaN,NaN,53.95800,...,1154.0,en,http://www.twitter.com/MarketCurrents/status/7...,False,NaN,NaN,NaN,"$GOOG,$GOOGL",NaN,http://seekingalpha.com/news/3188874-google-fi...
16,742999859876237316,2016-06-15,08:39,TalkMarkets Recap,MarketsRecap,A recap of our day's most popular headlines. ...,These 3 Stocks Will Surprise Investors This Ea...,1.0,1.0,NaN,...,243.0,en,http://www.twitter.com/MarketsRecap/status/742...,False,NaN,NaN,NaN,"$ADBE,$TTWO,$ANET,$AAPL,$AMZN,$FB,$GOOGL",NaN,http://goo.gl/yWr8F3
17,742994944651055104,2016-06-15,08:19,JennaKingtin1978,kingtin1978,NaN,HTS Horizons BetaPro S&amp;P/TSX 60 Bear Plus ...,NaN,NaN,NaN,...,37.0,en,http://www.twitter.com/kingtin1978/status/7429...,False,NaN,NaN,"#share,#tradeideas","$HTS,$GOOGL,$VXX,$EWG",NaN,http://dlvr.it/LZ24r4
18,742993571133952000,2016-06-15,08:14,MustWatchStocks,WatchMust,NaN,"GOOGL GoPro, Inc. Yield\nhttps://t.co/LA4ddiAM...",1.0,NaN,NaN,...,35.0,en,http://www.twitter.com/WatchMust/status/742993...,False,NaN,NaN,"#stocks,#tradeideas","$GOOGL,$TWTR,$AGEN,$ABX",NaN,http://dlvr.it/LZ1y8b
19,742993484861345792,2016-06-15,08:13,TheCountryCaller,TheCountryCallr,TheCountryCaller aims to be the epitome of all...,Alphabet Launches Enterprise Assistant Springb...,NaN,NaN,30.26715,...,24.0,en,http://www.twitter.com/TheCountryCallr/status/...,False,NaN,NaN,NaN,$GOOGL,http://pbs.twimg.com/media/Ck-kohEWsAAcgR8.jpg,http://goo.gl/Xr5f9l
20,742993275578142720,2016-06-15,08:12,Ø®Ø¯Ù…Ù‡ Ø§Ù„Ø¹Ù…Ù„Ø§Ø¡,bboptions1,NaN,RT @veryFatcat: My cat is running the algos fo...,NaN,1.0,NaN,...,6.0,en,http://www.twitter.com/bboptions1/status/74299...,True,@veryFatcat,"@veryFatcat,@carlquintanilla",NaN,"$spx,$VIX,$VXX,$AAPL,$AMZN,$NFLX,$FIT,$GOOGL",NaN,http://twitter.com/RTarabic/status/70533794699...
21,742991915134652417,2016-06-15,08:07,dexoidan,dexoidan,"I have 145,582 Followers. Try to make economic...",$GOOGL $FB French killer's Facebook broadcast ...,NaN,NaN,NaN,...,42.0,en,http://www.twitter.com/dexoidan/status/7429919...,False,NaN,NaN,"#Finance,#Stocks","$GOOGL,$FB",NaN,http://goo.gl/6yzLM9
22,742982165835702272,2016-06-15,07:28,Crypto Leprechaun,DarbyOGill_,Buying shitcoins again and taking the piss..,RT @DarbyOGill_: Sign up for free on 1broker w...,NaN,2.0,53.33306,...,103.0,en,http://www.twitter.com/DarbyOGill_/status/7429...,True,@DarbyOGill_,@DarbyOGill_,#Forex,"$BTC,$APPL,$FB,$GOOGL,$GOLD",NaN,https://1broker.com/m/r.php?i=2705
23,742977714609623040,2016-06-15,07:11,thejudgewill451,thejudgewill451,NaN,XLE Financial Select Sector SPDR Fund Company ...,NaN,NaN,NaN,...,31.0,es,http://www.twitter.com/thejudgewill451/status/...,False,NaN,NaN,"#tradeideas,#nasdaq","$XLE,$GOOGL,$LABU,$GBSN",NaN,http://dlvr.it/LZ0nDh
24,742974180287729664,2016-06-15,06:57,amystocks21334,amystocks21334,NaN,TLT Direxion Daily 20+ Year Treasury Bull 3x S...,NaN,NaN,NaN,...,38.0,en,http://www.twitter.com/amystocks21334/status/7...,False,NaN,NaN,"#stock,#nasdaq","$TLT,$FXA,$VMRI,$GOOGL",NaN,http://dlvr.it/LZ0WC5
25,742965714768760832,2016-06-15,06:23,Ro Patel,Ro_Patel,"Sell a man a fish, he eats for a day, teach a ...",Altering the deal: why Tony Fadell left Nest â€”...,NaN,NaN,NaN,...,44.0,en,http://www.twitter.com/Ro_Patel/status/7429657...,False,NaN,NaN,NaN,"$GOOG,$GOOGL",NaN,http://www.theverge.com/2016/6/7/11874670/nest...
26,742947772110868480,2016-06-15,05:12,ezzmoney2day,ezzmoney2day,NaN,XLB Materials Select Sector SPDR Fund Message ...,NaN,NaN,NaN,...,38.0,en,http://www.twitter.com/ezzmoney2day/status/742...,False,NaN,NaN,"#tradeideas,#invest","$XLB,$MEG.TO,$SIL,$GOOGL",NaN,http://dlvr.it/LYywmp
27,742953288245608449,2016-06-15,05:34,Eric Price,ortizandcrew,Eternal Bull,RT @theflynews: On The Fly: Top stock stories ...,NaN,1.0,NaN,...,81.0,en,http://www.twitter.com/ortizandcrew/status/742...,True,@theflynews,@theflynews,NaN,"$NFLX,$GOOG,$GOOGL,$T,$VZ,$VG,$NXTM,$DVA,$FOLD...",NaN,http://bit.ly/28C4z6T
28,742951479028383745,2016-06-15,05:26,Bluestone Financial,bluestonefinanz,Great Investment Ideas Do Not Necessarily Repr...,RT @sonycomeback: $SNE #SonyE3 BOOK VALUE 2X ...,NaN,1.0,NaN,...,32.0,en,http://www.twitter.com/bluestonefinanz/status/...,True,@sonycomeback,@sonycomeback,"#SonyE3,#E3,#e32016","$SNE,$MSFT,$MSFT,$SNE,$FB,$AAPL,$GOOG,$GOOGL,$...",NaN,NaN
29,742951362087030785,2016-06-15,05:26,Bluestone Financial,bluestonefinanz,Great Investment Ideas Do Not Necessarily Repr...,RT @sonycomeback: $SNE Sony #Xperia X has a 23...,NaN,1.0,NaN,...,32.0,en,http://www.twitter.com/bluestonefinanz/status/...,True,@sonycomeback,"@sonycomeback,@jimcramer",#Xperia,"$SNE,$AAPL,$GOOGL,$SSNLF,$MSFT,$T",NaN,http://bgr.com/2016/06/14/sony-xperia-x-preord...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
29355,714837019952701442,2016-03-29,15:30,AAPL Stock Alerts,SAlphaAAPL,News and articles about AAPL from Seeking Alph...,Apple's New Pragmatism https://t.co/Z2RspjJtC7...,NaN,NaN,53.95800,...,45.0,en,http://www.twitter.com/SAlphaAAPL/status/71483...,False,NaN,NaN,NaN,"$GOOG,$MSFT,$TSM,$GOOGL,$AAPL",NaN,http://seekingalpha.com/article/3960216-apples...
29356,714836535548321792,2016-03-29,15:28,AznOptions,aznboi27,Options Trader Focused on Technology and Finance,$AMZN $FB $NFLX $MSFT $GOOGL $AAPL tech is on ...,1.0,NaN,NaN,...,67.0,en,http://www.twitter.com/aznboi27/status/7148365...,False,NaN,NaN,NaN,"$AMZN,$FB,$NFLX,$MSFT,$GOOGL,$AAPL",NaN,NaN
29357,714836039630786565,2016-03-29,15:26,Carolyn Marshall,kiwitrader24,Trading full-time since 2005. My trades are al...,FANGB $FB $AMZN $NFLX $GOOGL $BIDU\n\nThey don...,NaN,NaN,41.85003,...,126.0,en,http://www.twitter.com/kiwitrader24/status/714...,False,NaN,NaN,NaN,"$FB,$AMZN,$NFLX,$GOOGL,$BIDU",NaN,NaN
29358,714836026380955648,2016-03-29,15:26,Warren Bevan,iTraderz,Swing/medium-term trader using technical analy...,Great action from $GOOGL as well here.,NaN,NaN,45.41117,...,55.0,en,http://www.twitter.com/iTraderz/status/7148360...,False,NaN,NaN,NaN,$GOOGL,NaN,NaN
29359,714835853357527040,2016-03-29,15:25,Jacobâ„¢,JacobUSMCGS,USMC turned GS. Narcissistic equity trader out...,As long as $GOOGL is at least doubling the gai...,NaN,NaN,NaN,...,93.0,en,http://www.twitter.com/JacobUSMCGS/status/7148...,False,NaN,NaN,NaN,$GOOGL,NaN,NaN
29360,714835625954959360,2016-03-29,15:24,Scott Redler,RedDogT3,"Chief Strategist T3Live/T3TradingGroup, freque...",Relative strength in high beta tech early was ...,4.0,1.0,53.95800,...,1417.0,en,http://www.twitter.com/RedDogT3/status/7148356...,False,NaN,NaN,NaN,"$amzn,$nflx,$fb,$googl,$aapl",NaN,https://twitter.com/reddogt3/status/7148152719...
29361,714835564877447168,2016-03-29,15:24,US BANKRUPTCY,20trilliondeb,US bankruptcy is coming,$SPX https://t.co/yXdKYPVPp5 #BEARMARKET 2016...,7.0,4.0,NaN,...,8.0,en,http://www.twitter.com/20trilliondeb/status/71...,False,NaN,NaN,"#BEARMARKET,#stocks,#stockmarket","$SPX,$spy,$VIX,$TVIX,$UVXY,$VXX,$GOOGL,$FB,$C,...",http://pbs.twimg.com/media/CegFbv_WsAAIKHr.jpg,NaN
29362,714834880580993025,2016-03-29,15:21,Son Nguyen,son2tweets,"Investor, #ChicagoBooth MBA, CFA. Opinions are...",@SkeleCap @modestproposal1 @max02050 @Bluegras...,NaN,NaN,41.85003,...,18.0,en,http://www.twitter.com/son2tweets/status/71483...,False,NaN,"@SkeleCap,@modestproposal1,@max02050,@Bluegras...",NaN,$GOOGL,NaN,NaN
29363,714834448529776642,2016-03-29,15:19,Day Traders Group,DayTradersGroup,"Trade along side world class options traders, ...",scaling out and locking gains on our 580 calls...,5.0,45.0,53.95800,...,64.0,en,http://www.twitter.com/DayTradersGroup/status/...,False,NaN,NaN,NaN,"$AAPL,$GOOGL,$AMZN,$PCLN,$AZO",NaN,http://twitter.com/DayTradersGroup/status/7148...
29364,714834443911843842,2016-03-29,15:19,Tim Parker,autumnalcity87,Good losses are due to ungovernable fortune. ...,.@autumnalcity87 strong. $GOOGL,NaN,NaN,NaN,...,150.0,en,http://www.twitter.com/autumnalcity87/status/7...,False,NaN,@autumnalcity87,NaN,$GOOGL,NaN,NaN
29365,714834429454192640,2016-03-29,15:19,$18trilliondeb,18trilliondeb,US bankruptcy is coming,RT @ppprophet: $DJI = 6000 pts soon! #BEARMA...,NaN,20.0,NaN,...,6.0,en,http://www.twitter.com/18trilliondeb/status/71...,True,@ppprophet,@ppprophet,"#BEARMARKET,#stocks,#stockmarket,#trading","$DJI,$VIX,$TVIX,$UVXY,$VXX,$GOOGL,$FB,$C,$JPM,...",NaN,NaN
29366,714834331982827520,2016-03-29,15:19,$18trilliondeb,18trilliondeb,US bankruptcy is coming,RT @ppprophet: $SPX = 666 pts soon! #BEARMAR...,NaN,13.0,NaN,...,6.0,en,http://www.twitter.com/18trilliondeb/status/71...,True,@ppprophet,@ppprophet,"#BEARMARKET,#stocks,#stockmarket,#trading","$SPX,$VIX,$TVIX,$UVXY,$VXX,$GOOGL,$FB,$C,$JPM,...",NaN,NaN
29367,714833843878891520,2016-03-29,15:17,Christian Rohlinger,cprohlinger,Intermediate Trader looking to develop into a ...,$FB approaching .886 retracement @ 115.22. $GO...,1.0,1.0,NaN,...,1.0,en,http://www.twitter.com/cprohlinger/status/7148...,False,NaN,NaN,NaN,"$FB,$GOOGL",NaN,NaN
29368,714833467259895808,2016-03-29,15:15,Natalia Angulo H.,natisangulorico,Editor/reporter @IndustryDive's @MarketingDive...,RT @marketingdive: Google revamps @adwords for...,NaN,1.0,47.50012,...,150.0,en,http://www.twitter.com/natisangulorico/status/...,True,@marketingdive,"@marketingdive,@adwords,@davidkonline",NaN,$GOOGL,http://pbs.twimg.com/media/CeuX1D5WsAAzWS_.jpg,http://bit.ly/1MyFFxa
29369,714833292005023744,2016-03-29,15:15,Marketing Dive,marketingdive,"Daily marketing news on: social media, digital...",Google revamps @adwords for a mobile-first mar...,NaN,1.0,47.50012,...,319.0,en,http://www.twitter.com/marketingdive/status/71...,False,NaN,"@adwords,@davidkonline",NaN,$GOOGL,http://pbs.twimg.com/media/CeuX1D5WsAAzWS_.jpg,http://bit.ly/1MyFFxa
29370,714833092498706433,2016-03-29,15:14,deafdaytrader,deafdaytrader,I look for good bottom stocks to be playable f...,$GOOGL so nice for calls,1.0,NaN,NaN,...,32.0,en,http://www.twitter.com/deafdaytrader/status/71...,False,NaN,NaN,NaN,$GOOGL,NaN,NaN
29371,714832442713104384,2016-03-29,15:11,CapCube Sez,CapCube,"Trader, Investor, Entrepreneur. Dad. Stocks & ...",It's a FANG kind of day $FB $AMZN $NFLX $GOOGL,NaN,NaN,NaN,...,107.0,en,http://www.twitter.com/CapCube/status/71483244...,False,NaN,NaN,NaN,"$FB,$AMZN,$NFLX,$GOOGL",NaN,NaN
29372,714830886076702720,2016-03-29,15:05,John,johnk07041955,Old American,Commented on April Dividend Brings CEFL Yield ...,NaN,NaN,42.09780,...,NaN,en,http://www.twitter.com/johnk07041955/status/71...,False,NaN,NaN,NaN,"$AGNC,$BRK.B,$BTU,$CY,$EDD,$GOOG,$GOOGL,$RVT,$...",NaN,http://seekingalpha.com/article/3961368-april-...
29373,714830830904983552,2016-03-29,15:05,Daniel Wilkinson,wilkinson991,"Trustworthy, ethical, discreet, well organized...",$FB Favorite #FANG #stock. Second comes $GOOGL.,NaN,NaN,NaN,...,31.0,en,http://www.twitter.com/wilkinson991/status/714...,False,NaN,NaN,"#FANG,#stock","$FB,$GOOGL",NaN,NaN
29374,714830296214937600,2016-03-29,15:03,Soldomi,soldomi15,NaN,RT @SAI: This new technology is changing web a...,NaN,8.0,NaN,...,NaN,en,http://www.twitter.com/soldomi15/status/714830...,True,@SAI,@SAI,NaN,"$GOOG,$GOOGL",http://pbs.twimg.com/media/CeuRTaIWsAAvvHR.jpg,http://read.bi/25ugHp9
29375,714830280742346753,2016-03-29,15:03,Victor Tellegio,VictorTellegio,I Trade Options/ Futures|Music Addict|Sports. ...,I'm in $googl calls btw,NaN,NaN,NaN,...,28.0,en,http://www.twitter.com/VictorTellegio/status/7...,False,NaN,NaN,NaN,$googl,NaN,NaN
29376,714829477377781760,2016-03-29,15:00,Trending Articles SA,SAlphaTrending,The top trending articles written by Seeking A...,Apple Vs. FBI: Winning By Coming Up Short http...,1.0,2.0,53.95800,...,345.0,en,http://www.twitter.com/SAlphaTrending/status/7...,False,NaN,NaN,NaN,"$BBRY,$GOOG,$MSFT,$GOOGL,$AAPL",NaN,http://seekingalpha.com/article/3961662-apple-...
29377,714829008739962880,2016-03-29,14:58,PressCaster,PressCaster,Simple. Easy. Cost effective! Unlimited Releas...,RT @businessinsider: This new technology is ch...,NaN,20.0,51.58774,...,27.0,en,http://www.twitter.com/PressCaster/status/7148...,True,@businessinsider,@businessinsider,NaN,"$GOOG,$GOOGL",http://pbs.twimg.com/media/CeuRTAsWAAAkDyu.jpg,http://read.bi/25ugHp9
29378,714828817223835648,2016-03-29,14:57,raiko karvonen,rapeka,NaN,RT @SAI: This new technology is changing web a...,NaN,8.0,NaN,...,211.0,en,http://www.twitter.com/rapeka/status/714828817...,True,@SAI,@SAI,NaN,"$GOOG,$GOOGL",http://pbs.twimg.com/media/CeuRTaIWsAAvvHR.jpg,http://read.bi/25ugHp9
29379,714828456312184832,2016-03-29,14:55,David Moadel,davidmoadel,I am not licensed or registered to provide fin...,$FREE just when you thought it couldn't get an...,NaN,NaN,NaN,...,341.0,en,http://www.twitter.com/davidmoadel/status/7148...,False,NaN,NaN,"#pennystocks,#stocks,#stockmarket,#finance","$FREE,$SPY,$GOOG,$GOOGL,$QQQ,$NFLX,$AMZN,$FB",NaN,NaN
29380,714828398179311616,2016-03-29,14:55,Geospatial Solutions,Geospatech,Bring the world closure to geospatial technolo...,businessinsider: This new technology is changi...,NaN,NaN,9.05785,...,106.0,en,http://www.twitter.com/Geospatech/status/71482...,False,NaN,NaN,NaN,"$GOOG,$GOOGL",http://pbs.twimg.com/media/CeuRTAsWAAAkDyu.jpg,http://read.bi/25ugHp9
29381,714828243472244737,2016-03-29,14:55,InvestorPlace,InvestorPlace,We provide investors with access to free stock...,$GOOGL Takes Too Much Heat - https://t.co/i7Qp...,1.0,NaN,39.08400,...,237.0,en,http://www.twitter.com/InvestorPlace/status/71...,False,NaN,NaN,NaN,$GOOGL,NaN,http://investorplace.com/2016/03/alphabet-goog...
29382,714828151386476544,2016-03-29,14:54,Insider News,insider8news,Insider News For Smart People,This new technology is changing web advertisin...,NaN,NaN,NaN,...,94.0,en,http://www.twitter.com/insider8news/status/714...,False,NaN,NaN,NaN,"$GOOG,$GOOGL",http://pbs.twimg.com/media/CeuRTAsWAAAkDyu.jpg,http://read.bi/25ugHp9
29383,714828046126202880,2016-03-29,14:54,Jake Catskill,JakeCatskill,"Bushwick Capital, LLC \nLong/Short discretionary.","""FANG"" stocks all pretty strong. $FB $AMZN $NF...",NaN,NaN,49.18804,...,59.0,en,http://www.twitter.com/JakeCatskill/status/714...,False,NaN,NaN,NaN,"$FB,$AMZN,$NFLX,$GOOGL,$QQQ,$AAPL",NaN,NaN
29384,714827827972018176,2016-03-29,14:53,Garth Vickers,GarthVickers,"#1 best selling author, international motivati...","RT businessinsider ""This new technology is cha...",NaN,NaN,NaN,...,84.0,en,http://www.twitter.com/GarthVickers/status/714...,False,NaN,NaN,NaN,"$GOOG,$GOOGL",http://pbs.twimg.com/media/CeuRTAsWAAAkDyu.jpg,http://read.bi/25ugHp9

In [60]:
df2=df2.drop(['Hour', 'User Name', 'Nickname', 'Bio', 'Favs', 'RTs', 'Latitude', 'Longitude', 'Country',
       'Place (as appears on Bio)', 'Profile picture',
       'Following', 'Listed', 'Tweet language (ISO 639-1)', 'Tweet Url',
       'Is a RT', 'Original Tweet User Name', 'User Mentions', 'Hashtags',
       'Symbols', 'Media', 'URLs'], axis=1)

In [61]:
df2

,Tweet Id,Date,Tweet content,Followers
0,743031249682477057,2016-06-15,RT @johnscharts: Similar to $GOOGL: $NFLX is s...,52
1,743031012406394880,2016-06-15,Similar to $GOOGL: $NFLX is showing reversal s...,2530
2,743030242688696321,2016-06-15,"#consumer, #jobs New #OT rules | ""OVERTIME: It...",3177
3,743029037858234368,2016-06-15,$GOOGL:\n\nIs Dallas the Next Destination for ...,806
4,743028676883779584,2016-06-15,Unusual Call Activity https://t.co/4jDlRqXapi ...,4864
5,743028189421797376,2016-06-15,$SPY $FB $IWM $IBB $AMZN $GOOGL Pay Attention ...,12436
6,743019479056187393,2016-06-15,$MSFT $AAPL $GOOGL:\n\nApple Tries to Limit Go...,806
7,743017272495747072,2016-06-15,Google Fiber explores Dallas https://t.co/lsdB...,6
8,743016380648165376,2016-06-15,#YouTube is built on the back of stolen conten...,5172
9,743014162373193729,2016-06-15,"Andreas Halvorsen Buys Facebook, Amazon, Maste...",5622
10,743011904533188608,2016-06-15,RT @MarketsRecap: These 3 Stocks Will Surprise...,1198
11,743011292127072257,2016-06-15,RT @Dealogic: $GOOGL buying $TWTR predicted to...,1551
12,743010029658210304,2016-06-15,RT @SAlphaTech: Google Fiber explores Dallas h...,354
13,743007354879254528,2016-06-15,Google Fiber explores Dallas https://t.co/FRVd...,356
14,743007353688072192,2016-06-15,Google Fiber explores Dallas https://t.co/2NGy...,3699
15,743007352429805568,2016-06-15,Google Fiber explores Dallas https://t.co/jqSd...,21916
16,742999859876237316,2016-06-15,These 3 Stocks Will Surprise Investors This Ea...,377
17,742994944651055104,2016-06-15,HTS Horizons BetaPro S&amp;P/TSX 60 Bear Plus ...,86
18,742993571133952000,2016-06-15,"GOOGL GoPro, Inc. Yield\nhttps://t.co/LA4ddiAM...",113
19,742993484861345792,2016-06-15,Alphabet Launches Enterprise Assistant Springb...,58
20,742993275578142720,2016-06-15,RT @veryFatcat: My cat is running the algos fo...,215
21,742991915134652417,2016-06-15,$GOOGL $FB French killer's Facebook broadcast ...,136
22,742982165835702272,2016-06-15,RT @DarbyOGill_: Sign up for free on 1broker w...,3493
23,742977714609623040,2016-06-15,XLE Financial Select Sector SPDR Fund Company ...,64
24,742974180287729664,2016-06-15,TLT Direxion Daily 20+ Year Treasury Bull 3x S...,73
25,742965714768760832,2016-06-15,Altering the deal: why Tony Fadell left Nest â€”...,571
26,742947772110868480,2016-06-15,XLB Materials Select Sector SPDR Fund Message ...,58
27,742953288245608449,2016-06-15,RT @theflynews: On The Fly: Top stock stories ...,8030
28,742951479028383745,2016-06-15,RT @sonycomeback: $SNE #SonyE3 BOOK VALUE 2X ...,289
29,742951362087030785,2016-06-15,RT @sonycomeback: $SNE Sony #Xperia X has a 23...,289
...,...,...,...,...
29355,714837019952701442,2016-03-29,Apple's New Pragmatism https://t.co/Z2RspjJtC7...,1889
29356,714836535548321792,2016-03-29,$AMZN $FB $NFLX $MSFT $GOOGL $AAPL tech is on ...,1038
29357,714836039630786565,2016-03-29,FANGB $FB $AMZN $NFLX $GOOGL $BIDU\n\nThey don...,2835
29358,714836026380955648,2016-03-29,Great action from $GOOGL as well here.,1256
29359,714835853357527040,2016-03-29,As long as $GOOGL is at least doubling the gai...,1314
29360,714835625954959360,2016-03-29,Relative strength in high beta tech early was ...,42086
29361,714835564877447168,2016-03-29,$SPX https://t.co/yXdKYPVPp5 #BEARMARKET 2016...,93
29362,714834880580993025,2016-03-29,@SkeleCap @modestproposal1 @max02050 @Bluegras...,428
29363,714834448529776642,2016-03-29,scaling out and locking gains on our 580 calls...,101465
29364,714834443911843842,2016-03-29,.@autumnalcity87 strong. $GOOGL,4359
29365,714834429454192640,2016-03-29,RT @ppprophet: $DJI = 6000 pts soon! #BEARMA...,81
29366,714834331982827520,2016-03-29,RT @ppprophet: $SPX = 666 pts soon! #BEARMAR...,81
29367,714833843878891520,2016-03-29,$FB approaching .886 retracement @ 115.22. $GO...,56
29368,714833467259895808,2016-03-29,RT @marketingdive: Google revamps @adwords for...,2114
29369,714833292005023744,2016-03-29,Google revamps @adwords for a mobile-first mar...,4297
29370,714833092498706433,2016-03-29,$GOOGL so nice for calls,596
29371,714832442713104384,2016-03-29,It's a FANG kind of day $FB $AMZN $NFLX $GOOGL,1683
29372,714830886076702720,2016-03-29,Commented on April Dividend Brings CEFL Yield ...,34
29373,714830830904983552,2016-03-29,$FB Favorite #FANG #stock. Second comes $GOOGL.,173
29374,714830296214937600,2016-03-29,RT @SAI: This new technology is changing web a...,31
29375,714830280742346753,2016-03-29,I'm in $googl calls btw,644
29376,714829477377781760,2016-03-29,Apple Vs. FBI: Winning By Coming Up Short http...,12227
29377,714829008739962880,2016-03-29,RT @businessinsider: This new technology is ch...,830
29378,714828817223835648,2016-03-29,RT @SAI: This new technology is changing web a...,356
29379,714828456312184832,2016-03-29,$FREE just when you thought it couldn't get an...,4853
29380,714828398179311616,2016-03-29,businessinsider: This new technology is changi...,500
29381,714828243472244737,2016-03-29,$GOOGL Takes Too Much Heat - https://t.co/i7Qp...,6004
29382,714828151386476544,2016-03-29,This new technology is changing web advertisin...,190
29383,714828046126202880,2016-03-29,"""FANG"" stocks all pretty strong. $FB $AMZN $NF...",745
29384,714827827972018176,2016-03-29,"RT businessinsider ""This new technology is cha...",3177

In [62]:
datadict={}
followerdict={}
datelist=df2.Date.unique()
count=0
temp=[]
follower_count=0
for i in range(len(df2.index)):
    if datelist[count]==df2.iloc[i]['Date']:
        temp.append(df2.iloc[i]['Tweet content'])
        follower_count+=df2.iloc[i]['Followers']
    else:
        datadict[datelist[count]]=temp
        followerdict[datelist[count]]=follower_count
        count+=1
        temp=[]
        follower_count=0
        temp.append(df2.iloc[i]['Tweet content'])
        follower_count+=df2.iloc[i]['Followers']

In [63]:
for i in datadict.keys():
    datadict[i]="".join(datadict[i])

In [64]:
def get_nrc_data():
    nrc = "NRC-emotion-lexicon-wordlevel-alphabetized-v0.92.txt"
    count=0
    emotion_dict=dict()
    with open(nrc,'r') as f:
        all_lines = list()
        for line in f:
            if count < 46:
                count+=1
                continue
            line = line.strip().split('\t')
            if int(line[2]) == 1:
                if emotion_dict.get(line[0]):
                    emotion_dict[line[0]].append(line[1])
                else:
                    emotion_dict[line[0]] = [line[1]]
    return emotion_dict


def emotion_analyzer(text,emotion_dict=get_nrc_data()):
    #Set up the result dictionary
    emotions = {x for y in emotion_dict.values() for x in y}
    emotion_count = dict()
    for emotion in emotions:
        emotion_count[emotion] = 0

    #Analyze the text and normalize by total number of words
    total_words = len(text.split())
    for word in text.split():
        if emotion_dict.get(word):
            for emotion in emotion_dict.get(word):
                emotion_count[emotion] += 1/len(text.split())
    return emotion_count

In [65]:
def comparative_emotion_analyzer(text_tuples,object_name="Tweets",print_output=False):
    if print_output:
        print("%-20s %1s\t%1s %1s %1s %1s   %1s %1s %1s %1s"%(object_name,
                                                              "fear","trust","negative","positive",
                                                              "joy","disgust","anticip", "sadness",
                                                              "surprise"))
    import pandas as pd
    df = pd.DataFrame(columns=[object_name,'Fear','Trust','Negative',
                           'Positive','Joy','Disgust','Anticipation',
                           'Sadness','Surprise'],)
    df.set_index(object_name,inplace=True)
    
    output = df    
    for text_tuple in text_tuples:
        text = text_tuple[1] 
        result = emotion_analyzer(text)
        if print_output:
            print("%-20s %1.2f\t%1.2f\t%1.2f\t%1.2f\t%1.2f\t%1.2f\t%1.2f\t%1.2f\t%1.2f"%(
                text_tuple[1][0:20],result['fear'],result['trust'],
                  result['negative'],result['positive'],result['joy'],result['disgust'],
                  result['anticipation'],result['sadness'],result['surprise']))
        df.loc[text_tuple[0]] = [result['fear'],result['trust'],
                  result['negative'],result['positive'],result['joy'],result['disgust'],
                  result['anticipation'],result['sadness'],result['surprise']]
    return output

In [66]:
df2 = pd.DataFrame(columns=['Fear','Trust','Negative',
                           'Positive','Joy','Disgust','Anticipation',
                           'Sadness','Surprise','follower_count'])
coubt=0
for i in datadict.keys():
    df1=comparative_emotion_analyzer([[i,datadict[i]]],object_name='google Tweets',print_output=False)
    df2=df2.append(df1,ignore_index=False)

df2

/Users/xiyuyang/anaconda3/lib/python3.6/site-packages/pandas/core/frame.py:6211: FutureWarning: Sorting because non-concatenation axis is not aligned. A future version
of pandas will change to not sort by default.

To accept the future behavior, pass 'sort=False'.

To retain the current behavior and silence the warning, pass 'sort=True'.

  sort=sort)

,Anticipation,Disgust,Fear,Joy,Negative,Positive,Sadness,Surprise,Trust,follower_count
2016-06-15,0.001800,0.001800,0.000900,0.000000,0.009001,0.004500,0.000000,0.001800,0.002700,NaN
2016-06-14,0.007916,0.000609,0.001827,0.005074,0.008930,0.010757,0.002030,0.005277,0.009539,NaN
2016-06-13,0.012598,0.000900,0.005399,0.005174,0.006974,0.026772,0.002475,0.004274,0.016423,NaN
2016-06-12,0.008077,0.008582,0.003534,0.001514,0.019687,0.008582,0.001514,0.001514,0.004543,NaN
2016-06-11,0.007812,0.001465,0.004883,0.002930,0.011719,0.009277,0.003418,0.003906,0.005859,NaN
2016-06-10,0.010336,0.001723,0.003302,0.003445,0.006029,0.008613,0.003302,0.003302,0.005024,NaN
2016-06-07,0.003610,0.000000,0.000903,0.002708,0.005415,0.006318,0.000000,0.000000,0.007220,NaN
2016-06-06,0.010871,0.001004,0.004850,0.003680,0.009032,0.015053,0.002676,0.002843,0.010871,NaN
2016-06-05,0.008673,0.004337,0.004337,0.003903,0.015611,0.015178,0.010841,0.003903,0.012576,NaN
2016-06-04,0.006410,0.005698,0.012108,0.002849,0.019231,0.022792,0.006410,0.002849,0.006410,NaN
2016-06-03,0.008374,0.001092,0.004915,0.005097,0.010559,0.015110,0.006554,0.005461,0.010377,NaN
2016-06-02,0.012309,0.002238,0.003730,0.004849,0.012495,0.013801,0.004849,0.005035,0.013614,NaN
2016-06-01,0.011114,0.000667,0.003112,0.002000,0.006890,0.013559,0.001111,0.004001,0.006224,NaN
2016-05-31,0.013740,0.002147,0.003435,0.002362,0.006655,0.006655,0.002147,0.004508,0.006870,NaN
2016-05-30,0.015553,0.005354,0.007904,0.010454,0.007904,0.015043,0.007394,0.011729,0.017083,NaN
2016-05-29,0.026459,0.012600,0.003780,0.018480,0.002940,0.021000,0.005880,0.021420,0.021000,NaN
2016-05-28,0.017787,0.004941,0.011858,0.009881,0.005435,0.014822,0.008399,0.017787,0.023715,NaN
2016-05-27,0.012437,0.000491,0.007364,0.005236,0.011455,0.017509,0.005236,0.004255,0.014400,NaN
2016-05-26,0.012001,0.002197,0.014875,0.006254,0.019777,0.020115,0.006930,0.005071,0.018594,NaN
2016-05-25,0.015635,0.001445,0.002891,0.006701,0.004730,0.014321,0.003022,0.003416,0.009460,NaN
2016-05-24,0.022810,0.004489,0.006552,0.005824,0.017957,0.016501,0.009221,0.008372,0.011041,NaN
2016-05-23,0.005848,0.001418,0.002127,0.002658,0.005139,0.008152,0.001418,0.001418,0.006025,NaN
2016-05-22,0.007095,0.000443,0.005765,0.011086,0.007095,0.017295,0.003104,0.002661,0.015078,NaN
2016-05-21,0.005309,0.003318,0.006967,0.002654,0.009290,0.011281,0.000664,0.006967,0.008626,NaN
2016-05-20,0.009996,0.001764,0.007350,0.004410,0.010584,0.018227,0.003234,0.003381,0.010437,NaN
2016-05-19,0.009824,0.004404,0.004291,0.006436,0.009146,0.016147,0.003613,0.005533,0.012534,NaN
2016-05-18,0.014184,0.001055,0.004689,0.004689,0.013129,0.013480,0.005744,0.004572,0.009378,NaN
2016-05-17,0.009824,0.001387,0.003121,0.006472,0.007166,0.012483,0.003699,0.005663,0.010287,NaN
2016-05-16,0.009402,0.002447,0.009660,0.010948,0.007857,0.021767,0.003478,0.001417,0.015714,NaN
2016-05-15,0.016044,0.000251,0.001003,0.001755,0.006769,0.014791,0.001755,0.001253,0.013788,NaN
...,...,...,...,...,...,...,...,...,...,...
2016-04-28,0.012685,0.005452,0.007233,0.004673,0.012574,0.014132,0.005452,0.004673,0.010793,NaN
2016-04-27,0.013446,0.002062,0.004751,0.004930,0.008874,0.016673,0.004034,0.003048,0.009502,NaN
2016-04-26,0.011185,0.001991,0.006066,0.004834,0.011848,0.012891,0.003318,0.002464,0.010900,NaN
2016-04-25,0.007043,0.000361,0.004424,0.002438,0.006230,0.009120,0.003251,0.002438,0.006501,NaN
2016-04-24,0.010884,0.000447,0.003280,0.008648,0.004175,0.018339,0.001938,0.001938,0.010288,NaN
2016-04-23,0.007741,0.001209,0.003387,0.002661,0.002661,0.009676,0.001451,0.004596,0.006773,NaN
2016-04-22,0.011584,0.003337,0.006864,0.006960,0.016112,0.016350,0.006864,0.004767,0.013252,NaN
2016-04-21,0.011035,0.001427,0.005119,0.005455,0.010657,0.013679,0.004406,0.003608,0.010657,NaN
2016-04-20,0.011477,0.000998,0.004865,0.009232,0.008608,0.014596,0.001996,0.003119,0.006487,NaN
2016-04-19,0.009274,0.001747,0.005376,0.002554,0.007124,0.012634,0.004435,0.002285,0.008602,NaN
2016-04-18,0.005249,0.000893,0.002680,0.001899,0.005249,0.005361,0.002122,0.003015,0.005361,NaN
2016-04-17,0.006318,0.001053,0.002457,0.002106,0.004914,0.005967,0.001053,0.002808,0.010179,NaN
2016-04-16,0.006706,0.001032,0.002837,0.003095,0.004127,0.016508,0.002321,0.003869,0.009028,NaN
2016-04-15,0.012985,0.000666,0.004828,0.005161,0.006659,0.013817,0.001998,0.003496,0.010654,NaN
2016-04-14,0.010691,0.000396,0.003960,0.002970,0.006731,0.009503,0.002376,0.003762,0.010097,NaN
2016-04-13,0.013948,0.000809,0.006064,0.004851,0.009096,0.012937,0.005256,0.004245,0.011320,NaN
2016-04-12,0.012350,0.001710,0.005890,0.004370,0.009690,0.011780,0.004560,0.004180,0.012540,NaN
2016-04-11,0.008661,0.000787,0.005512,0.002047,0.008504,0.013543,0.003780,0.001890,0.009449,NaN
2016-04-10,0.010800,0.000982,0.005400,0.003436,0.007855,0.008346,0.001964,0.004418,0.008346,NaN
2016-04-09,0.013561,0.001769,0.006486,0.002358,0.012382,0.013561,0.002948,0.004717,0.013561,NaN
2016-04-08,0.011632,0.000191,0.005530,0.004767,0.004005,0.012967,0.001907,0.005149,0.011060,NaN
2016-04-07,0.011669,0.002139,0.005834,0.003112,0.009529,0.016531,0.003890,0.003501,0.007001,NaN
2016-04-06,0.007459,0.000219,0.002413,0.003730,0.007679,0.008776,0.001536,0.003072,0.009434,NaN
2016-04-05,0.008983,0.000642,0.003529,0.001925,0.006096,0.008341,0.004171,0.002567,0.005454,NaN
2016-04-04,0.008965,0.003118,0.007991,0.003508,0.008380,0.007016,0.004483,0.004677,0.008186,NaN
2016-04-03,0.004915,0.000000,0.008738,0.001092,0.001638,0.009831,0.000546,0.009831,0.012561,NaN
2016-04-02,0.002187,0.000000,0.003644,0.000000,0.005102,0.004373,0.000729,0.002187,0.004373,NaN
2016-04-01,0.011417,0.001737,0.004716,0.001737,0.013651,0.013155,0.003475,0.004468,0.007694,NaN
2016-03-31,0.013947,0.001579,0.002368,0.005789,0.010789,0.017895,0.002105,0.002632,0.012632,NaN
2016-03-30,0.008618,0.001034,0.002241,0.003619,0.009307,0.013961,0.002241,0.002241,0.011203,NaN

In [67]:
for i in followerdict.keys():
    df2.follower_count.loc[i]=followerdict[i]

/Users/xiyuyang/anaconda3/lib/python3.6/site-packages/pandas/core/indexing.py:189: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  self._setitem_with_indexer(indexer, value)

In [68]:
df2

,Anticipation,Disgust,Fear,Joy,Negative,Positive,Sadness,Surprise,Trust,follower_count
2016-06-15,0.001800,0.001800,0.000900,0.000000,0.009001,0.004500,0.000000,0.001800,0.002700,212332
2016-06-14,0.007916,0.000609,0.001827,0.005074,0.008930,0.010757,0.002030,0.005277,0.009539,4413122
2016-06-13,0.012598,0.000900,0.005399,0.005174,0.006974,0.026772,0.002475,0.004274,0.016423,2652364
2016-06-12,0.008077,0.008582,0.003534,0.001514,0.019687,0.008582,0.001514,0.001514,0.004543,647515
2016-06-11,0.007812,0.001465,0.004883,0.002930,0.011719,0.009277,0.003418,0.003906,0.005859,744268
2016-06-10,0.010336,0.001723,0.003302,0.003445,0.006029,0.008613,0.003302,0.003302,0.005024,6054195
2016-06-07,0.003610,0.000000,0.000903,0.002708,0.005415,0.006318,0.000000,0.000000,0.007220,305868
2016-06-06,0.010871,0.001004,0.004850,0.003680,0.009032,0.015053,0.002676,0.002843,0.010871,5499488
2016-06-05,0.008673,0.004337,0.004337,0.003903,0.015611,0.015178,0.010841,0.003903,0.012576,1851030
2016-06-04,0.006410,0.005698,0.012108,0.002849,0.019231,0.022792,0.006410,0.002849,0.006410,390035
2016-06-03,0.008374,0.001092,0.004915,0.005097,0.010559,0.015110,0.006554,0.005461,0.010377,6452887
2016-06-02,0.012309,0.002238,0.003730,0.004849,0.012495,0.013801,0.004849,0.005035,0.013614,4112753
2016-06-01,0.011114,0.000667,0.003112,0.002000,0.006890,0.013559,0.001111,0.004001,0.006224,2873846
2016-05-31,0.013740,0.002147,0.003435,0.002362,0.006655,0.006655,0.002147,0.004508,0.006870,1165054
2016-05-30,0.015553,0.005354,0.007904,0.010454,0.007904,0.015043,0.007394,0.011729,0.017083,1402642
2016-05-29,0.026459,0.012600,0.003780,0.018480,0.002940,0.021000,0.005880,0.021420,0.021000,2005982
2016-05-28,0.017787,0.004941,0.011858,0.009881,0.005435,0.014822,0.008399,0.017787,0.023715,288882
2016-05-27,0.012437,0.000491,0.007364,0.005236,0.011455,0.017509,0.005236,0.004255,0.014400,5657352
2016-05-26,0.012001,0.002197,0.014875,0.006254,0.019777,0.020115,0.006930,0.005071,0.018594,4961737
2016-05-25,0.015635,0.001445,0.002891,0.006701,0.004730,0.014321,0.003022,0.003416,0.009460,7092360
2016-05-24,0.022810,0.004489,0.006552,0.005824,0.017957,0.016501,0.009221,0.008372,0.011041,10420914
2016-05-23,0.005848,0.001418,0.002127,0.002658,0.005139,0.008152,0.001418,0.001418,0.006025,3376756
2016-05-22,0.007095,0.000443,0.005765,0.011086,0.007095,0.017295,0.003104,0.002661,0.015078,2123759
2016-05-21,0.005309,0.003318,0.006967,0.002654,0.009290,0.011281,0.000664,0.006967,0.008626,5787932
2016-05-20,0.009996,0.001764,0.007350,0.004410,0.010584,0.018227,0.003234,0.003381,0.010437,5357101
2016-05-19,0.009824,0.004404,0.004291,0.006436,0.009146,0.016147,0.003613,0.005533,0.012534,9005807
2016-05-18,0.014184,0.001055,0.004689,0.004689,0.013129,0.013480,0.005744,0.004572,0.009378,21848520
2016-05-17,0.009824,0.001387,0.003121,0.006472,0.007166,0.012483,0.003699,0.005663,0.010287,9402633
2016-05-16,0.009402,0.002447,0.009660,0.010948,0.007857,0.021767,0.003478,0.001417,0.015714,8517389
2016-05-15,0.016044,0.000251,0.001003,0.001755,0.006769,0.014791,0.001755,0.001253,0.013788,1803631
...,...,...,...,...,...,...,...,...,...,...
2016-04-28,0.012685,0.005452,0.007233,0.004673,0.012574,0.014132,0.005452,0.004673,0.010793,2486070
2016-04-27,0.013446,0.002062,0.004751,0.004930,0.008874,0.016673,0.004034,0.003048,0.009502,10041337
2016-04-26,0.011185,0.001991,0.006066,0.004834,0.011848,0.012891,0.003318,0.002464,0.010900,10366985
2016-04-25,0.007043,0.000361,0.004424,0.002438,0.006230,0.009120,0.003251,0.002438,0.006501,2335541
2016-04-24,0.010884,0.000447,0.003280,0.008648,0.004175,0.018339,0.001938,0.001938,0.010288,3100593
2016-04-23,0.007741,0.001209,0.003387,0.002661,0.002661,0.009676,0.001451,0.004596,0.006773,4398740
2016-04-22,0.011584,0.003337,0.006864,0.006960,0.016112,0.016350,0.006864,0.004767,0.013252,22504935
2016-04-21,0.011035,0.001427,0.005119,0.005455,0.010657,0.013679,0.004406,0.003608,0.010657,20720069
2016-04-20,0.011477,0.000998,0.004865,0.009232,0.008608,0.014596,0.001996,0.003119,0.006487,5471447
2016-04-19,0.009274,0.001747,0.005376,0.002554,0.007124,0.012634,0.004435,0.002285,0.008602,6117055
2016-04-18,0.005249,0.000893,0.002680,0.001899,0.005249,0.005361,0.002122,0.003015,0.005361,5079343
2016-04-17,0.006318,0.001053,0.002457,0.002106,0.004914,0.005967,0.001053,0.002808,0.010179,1426549
2016-04-16,0.006706,0.001032,0.002837,0.003095,0.004127,0.016508,0.002321,0.003869,0.009028,5741292
2016-04-15,0.012985,0.000666,0.004828,0.005161,0.006659,0.013817,0.001998,0.003496,0.010654,5615910
2016-04-14,0.010691,0.000396,0.003960,0.002970,0.006731,0.009503,0.002376,0.003762,0.010097,2604839
2016-04-13,0.013948,0.000809,0.006064,0.004851,0.009096,0.012937,0.005256,0.004245,0.011320,1257674
2016-04-12,0.012350,0.001710,0.005890,0.004370,0.009690,0.011780,0.004560,0.004180,0.012540,1370910
2016-04-11,0.008661,0.000787,0.005512,0.002047,0.008504,0.013543,0.003780,0.001890,0.009449,2335363
2016-04-10,0.010800,0.000982,0.005400,0.003436,0.007855,0.008346,0.001964,0.004418,0.008346,253017
2016-04-09,0.013561,0.001769,0.006486,0.002358,0.012382,0.013561,0.002948,0.004717,0.013561,291816
2016-04-08,0.011632,0.000191,0.005530,0.004767,0.004005,0.012967,0.001907,0.005149,0.011060,2297802
2016-04-07,0.011669,0.002139,0.005834,0.003112,0.009529,0.016531,0.003890,0.003501,0.007001,3112113
2016-04-06,0.007459,0.000219,0.002413,0.003730,0.007679,0.008776,0.001536,0.003072,0.009434,5040818
2016-04-05,0.008983,0.000642,0.003529,0.001925,0.006096,0.008341,0.004171,0.002567,0.005454,942575
2016-04-04,0.008965,0.003118,0.007991,0.003508,0.008380,0.007016,0.004483,0.004677,0.008186,3336352
2016-04-03,0.004915,0.000000,0.008738,0.001092,0.001638,0.009831,0.000546,0.009831,0.012561,3260284
2016-04-02,0.002187,0.000000,0.003644,0.000000,0.005102,0.004373,0.000729,0.002187,0.004373,833434
2016-04-01,0.011417,0.001737,0.004716,0.001737,0.013651,0.013155,0.003475,0.004468,0.007694,1999362
2016-03-31,0.013947,0.001579,0.002368,0.005789,0.010789,0.017895,0.002105,0.002632,0.012632,1142140
2016-03-30,0.008618,0.001034,0.002241,0.003619,0.009307,0.013961,0.002241,0.002241,0.011203,1608581

In [69]:
import numpy as np
df2['Pct_change']=np.nan
# [i[:9] for i in rets.index.values()]

In [70]:
# d='2016-03-10T00:00:00.000000000'
# date=pd.to_datetime(d).date()
# date
a=[str(i)[:10] for i in rets.index.values]

In [71]:
for i in followerdict.keys():
    if i in a:
        df2.Pct_change.loc[i]=rets.GOOGL.loc[i]

/Users/xiyuyang/anaconda3/lib/python3.6/site-packages/pandas/core/indexing.py:189: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  self._setitem_with_indexer(indexer, value)

In [72]:
df2

,Anticipation,Disgust,Fear,Joy,Negative,Positive,Sadness,Surprise,Trust,follower_count,Pct_change
2016-06-15,0.001800,0.001800,0.000900,0.000000,0.009001,0.004500,0.000000,0.001800,0.002700,212332,0.007692
2016-06-14,0.007916,0.000609,0.001827,0.005074,0.008930,0.010757,0.002030,0.005277,0.009539,4413122,-0.000699
2016-06-13,0.012598,0.000900,0.005399,0.005174,0.006974,0.026772,0.002475,0.004274,0.016423,2652364,-0.008329
2016-06-12,0.008077,0.008582,0.003534,0.001514,0.019687,0.008582,0.001514,0.001514,0.004543,647515,NaN
2016-06-11,0.007812,0.001465,0.004883,0.002930,0.011719,0.009277,0.003418,0.003906,0.005859,744268,NaN
2016-06-10,0.010336,0.001723,0.003302,0.003445,0.006029,0.008613,0.003302,0.003302,0.005024,6054195,-0.001520
2016-06-07,0.003610,0.000000,0.000903,0.002708,0.005415,0.006318,0.000000,0.000000,0.007220,305868,-0.007082
2016-06-06,0.010871,0.001004,0.004850,0.003680,0.009032,0.015053,0.002676,0.002843,0.010871,5499488,-0.004032
2016-06-05,0.008673,0.004337,0.004337,0.003903,0.015611,0.015178,0.010841,0.003903,0.012576,1851030,NaN
2016-06-04,0.006410,0.005698,0.012108,0.002849,0.019231,0.022792,0.006410,0.002849,0.006410,390035,NaN
2016-06-03,0.008374,0.001092,0.004915,0.005097,0.010559,0.015110,0.006554,0.005461,0.010377,6452887,-0.006179
2016-06-02,0.012309,0.002238,0.003730,0.004849,0.012495,0.013801,0.004849,0.005035,0.013614,4112753,-0.003166
2016-06-01,0.011114,0.000667,0.003112,0.002000,0.006890,0.013559,0.001111,0.004001,0.006224,2873846,-0.000387
2016-05-31,0.013740,0.002147,0.003435,0.002362,0.006655,0.006655,0.002147,0.004508,0.006870,1165054,0.015254
2016-05-30,0.015553,0.005354,0.007904,0.010454,0.007904,0.015043,0.007394,0.011729,0.017083,1402642,NaN
2016-05-29,0.026459,0.012600,0.003780,0.018480,0.002940,0.021000,0.005880,0.021420,0.021000,2005982,NaN
2016-05-28,0.017787,0.004941,0.011858,0.009881,0.005435,0.014822,0.008399,0.017787,0.023715,288882,NaN
2016-05-27,0.012437,0.000491,0.007364,0.005236,0.011455,0.017509,0.005236,0.004255,0.014400,5657352,0.002052
2016-05-26,0.012001,0.002197,0.014875,0.006254,0.019777,0.020115,0.006930,0.005071,0.018594,4961737,0.001361
2016-05-25,0.015635,0.001445,0.002891,0.006701,0.004730,0.014321,0.003022,0.003416,0.009460,7092360,0.021046
2016-05-24,0.022810,0.004489,0.006552,0.005824,0.017957,0.016501,0.009221,0.008372,0.011041,10420914,-0.000181
2016-05-23,0.005848,0.001418,0.002127,0.002658,0.005139,0.008152,0.001418,0.001418,0.006025,3376756,0.004913
2016-05-22,0.007095,0.000443,0.005765,0.011086,0.007095,0.017295,0.003104,0.002661,0.015078,2123759,NaN
2016-05-21,0.005309,0.003318,0.006967,0.002654,0.009290,0.011281,0.000664,0.006967,0.008626,5787932,NaN
2016-05-20,0.009996,0.001764,0.007350,0.004410,0.010584,0.018227,0.003234,0.003381,0.010437,5357101,-0.002562
2016-05-19,0.009824,0.004404,0.004291,0.006436,0.009146,0.016147,0.003613,0.005533,0.012534,9005807,-0.000278
2016-05-18,0.014184,0.001055,0.004689,0.004689,0.013129,0.013480,0.005744,0.004572,0.009378,21848520,-0.017181
2016-05-17,0.009824,0.001387,0.003121,0.006472,0.007166,0.012483,0.003699,0.005663,0.010287,9402633,0.009305
2016-05-16,0.009402,0.002447,0.009660,0.010948,0.007857,0.021767,0.003478,0.001417,0.015714,8517389,-0.003165
2016-05-15,0.016044,0.000251,0.001003,0.001755,0.006769,0.014791,0.001755,0.001253,0.013788,1803631,NaN
...,...,...,...,...,...,...,...,...,...,...,...
2016-04-28,0.012685,0.005452,0.007233,0.004673,0.012574,0.014132,0.005452,0.004673,0.010793,2486070,-0.002799
2016-04-27,0.013446,0.002062,0.004751,0.004930,0.008874,0.016673,0.004034,0.003048,0.009502,10041337,-0.025658
2016-04-26,0.011185,0.001991,0.006066,0.004834,0.011848,0.012891,0.003318,0.002464,0.010900,10366985,0.012334
2016-04-25,0.007043,0.000361,0.004424,0.002438,0.006230,0.009120,0.003251,0.002438,0.006501,2335541,-0.011507
2016-04-24,0.010884,0.000447,0.003280,0.008648,0.004175,0.018339,0.001938,0.001938,0.010288,3100593,NaN
2016-04-23,0.007741,0.001209,0.003387,0.002661,0.002661,0.009676,0.001451,0.004596,0.006773,4398740,NaN
2016-04-22,0.011584,0.003337,0.006864,0.006960,0.016112,0.016350,0.006864,0.004767,0.013252,22504935,-0.042969
2016-04-21,0.011035,0.001427,0.005119,0.005455,0.010657,0.013679,0.004406,0.003608,0.010657,20720069,-0.002374
2016-04-20,0.011477,0.000998,0.004865,0.009232,0.008608,0.014596,0.001996,0.003119,0.006487,5471447,-0.014345
2016-04-19,0.009274,0.001747,0.005376,0.002554,0.007124,0.012634,0.004435,0.002285,0.008602,6117055,0.013215
2016-04-18,0.005249,0.000893,0.002680,0.001899,0.005249,0.005361,0.002122,0.003015,0.005361,5079343,0.006048
2016-04-17,0.006318,0.001053,0.002457,0.002106,0.004914,0.005967,0.001053,0.002808,0.010179,1426549,NaN
2016-04-16,0.006706,0.001032,0.002837,0.003095,0.004127,0.016508,0.002321,0.003869,0.009028,5741292,NaN
2016-04-15,0.012985,0.000666,0.004828,0.005161,0.006659,0.013817,0.001998,0.003496,0.010654,5615910,0.000181
2016-04-14,0.010691,0.000396,0.003960,0.002970,0.006731,0.009503,0.002376,0.003762,0.010097,2604839,0.006556
2016-04-13,0.013948,0.000809,0.006064,0.004851,0.009096,0.012937,0.005256,0.004245,0.011320,1257674,0.015664
2016-04-12,0.012350,0.001710,0.005890,0.004370,0.009690,0.011780,0.004560,0.004180,0.012540,1370910,-0.009171
2016-04-11,0.008661,0.000787,0.005512,0.002047,0.008504,0.013543,0.003780,0.001890,0.009449,2335363,-0.000548
2016-04-10,0.010800,0.000982,0.005400,0.003436,0.007855,0.008346,0.001964,0.004418,0.008346,253017,NaN
2016-04-09,0.013561,0.001769,0.006486,0.002358,0.012382,0.013561,0.002948,0.004717,0.013561,291816,NaN
2016-04-08,0.011632,0.000191,0.005530,0.004767,0.004005,0.012967,0.001907,0.005149,0.011060,2297802,0.000719
2016-04-07,0.011669,0.002139,0.005834,0.003112,0.009529,0.016531,0.003890,0.003501,0.007001,3112113,0.009870
2016-04-06,0.007459,0.000219,0.002413,0.003730,0.007679,0.008776,0.001536,0.003072,0.009434,5040818,-0.000382
2016-04-05,0.008983,0.000642,0.003529,0.001925,0.006096,0.008341,0.004171,0.002567,0.005454,942575,-0.014789
2016-04-04,0.008965,0.003118,0.007991,0.003508,0.008380,0.007016,0.004483,0.004677,0.008186,3336352,0.016311
2016-04-03,0.004915,0.000000,0.008738,0.001092,0.001638,0.009831,0.000546,0.009831,0.012561,3260284,NaN
2016-04-02,0.002187,0.000000,0.003644,0.000000,0.005102,0.004373,0.000729,0.002187,0.004373,833434,NaN
2016-04-01,0.011417,0.001737,0.004716,0.001737,0.013651,0.013155,0.003475,0.004468,0.007694,1999362,-0.014551
2016-03-31,0.013947,0.001579,0.002368,0.005789,0.010789,0.017895,0.002105,0.002632,0.012632,1142140,0.000169
2016-03-30,0.008618,0.001034,0.002241,0.003619,0.009307,0.013961,0.002241,0.002241,0.011203,1608581,0.019279

In [73]:
rets

Symbols         AAPL     GOOGL
Date
2016-03-10       NaN       NaN
2016-03-11  0.008185  0.016708
2016-03-14 -0.003228  0.006784
2016-03-15  0.020116  0.001410
2016-03-16  0.006252  0.004062
2016-03-17  0.008699  0.011481
2016-03-18  0.007771  0.005253
2016-03-21 -0.003856 -0.010136
2016-03-22 -0.006419  0.006009
2016-03-23  0.011686  0.006474
2016-03-24 -0.009485 -0.015917
2016-03-28  0.005025  0.006616
2016-03-29 -0.010472 -0.003293
2016-03-30  0.035847  0.019279
2016-03-31  0.009848  0.000169
2016-04-01 -0.008567 -0.014551
2016-04-04  0.015076  0.016311
2016-04-05 -0.008241 -0.014789
2016-04-06  0.006575 -0.000382
2016-04-07 -0.002540  0.009870
2016-04-08 -0.009459  0.000719
2016-04-11  0.000551 -0.000548
2016-04-12  0.003395 -0.009171
2016-04-13  0.013353  0.015664
2016-04-14  0.007401  0.006556
2016-04-15  0.004390  0.000181
2016-04-18 -0.028722  0.006048
2016-04-19 -0.009275  0.013215
2016-04-20 -0.011494 -0.014345
2016-04-21  0.002719 -0.002374
...              ...       ...
2016-05-05 -0.012605  0.011644
2016-05-06 -0.006702 -0.003916
2016-05-09 -0.003963  0.020359
2016-05-10  0.003548  0.011366
2016-05-11  0.001607  0.007565
2016-05-12 -0.008130 -0.011505
2016-05-13 -0.029336 -0.007350
2016-05-16  0.026556 -0.003165
2016-05-17  0.023379  0.009305
2016-05-18 -0.004125 -0.017181
2016-05-19  0.005098 -0.000278
2016-05-20  0.000000 -0.002562
2016-05-23  0.012997  0.004913
2016-05-24  0.014082 -0.000181
2016-05-25  0.014915  0.021046
2016-05-26  0.010236  0.001361
2016-05-27 -0.002408  0.002052
2016-05-31  0.001609  0.015254
2016-06-01 -0.005823 -0.000387
2016-06-02 -0.014341 -0.003166
2016-06-03  0.001947 -0.006179
2016-06-06  0.002045 -0.004032
2016-06-07  0.012858 -0.007082
2016-06-08 -0.002317  0.008496
2016-06-09 -0.005251 -0.003286
2016-06-10  0.000305 -0.001520
2016-06-13  0.001624 -0.008329
2016-06-14 -0.013882 -0.000699
2016-06-15  0.005138  0.007692
2016-06-16 -0.014005 -0.009470

[69 rows x 2 columns]

In [74]:
df3=df1.append(df2)

/Users/xiyuyang/anaconda3/lib/python3.6/site-packages/pandas/core/frame.py:6211: FutureWarning: Sorting because non-concatenation axis is not aligned. A future version
of pandas will change to not sort by default.

To accept the future behavior, pass 'sort=False'.

To retain the current behavior and silence the warning, pass 'sort=True'.

  sort=sort)

In [75]:
df3.info()

<class 'pandas.core.frame.DataFrame'>
Index: 77 entries, 2016-03-30 to 2016-03-30
Data columns (total 11 columns):
Anticipation      77 non-null float64
Disgust           77 non-null float64
Fear              77 non-null float64
Joy               77 non-null float64
Negative          77 non-null float64
Pct_change        53 non-null float64
Positive          77 non-null float64
Sadness           77 non-null float64
Surprise          77 non-null float64
Trust             77 non-null float64
follower_count    76 non-null float64
dtypes: float64(11)
memory usage: 7.2+ KB

In [76]:
df3.to_csv('final_data.csv')